exclude: [".gitignore"]
include: ["_pages", ".htaccess"]
defaults:
  -
    values:
      layout: "committee_page"

committees: [  
               "unsc",
               "disec",
               "ipc",
               "ls",
               "scrt",
               "specpol",
               "unfccc",
               "unhcr",
               "unhrc",
               "unhsc",
               "unmsc",
               "usnsc",
               "unw",
               "aippm"
            ]
